### ISSUE TITLE
Step 99: There was an error, check the console for more details

### ISSUE THREAD

**Issue by Entheologian** [aschmelyun/subvert#1]
Hi,

This is great and I hope to see this progress as this project can come in very handy!

I tried a couple of video clips and get the error above, but there are no errors on the console that I can see:
> subvert_1  |   2023-03-29 08:34:12 App\Jobs\ProcessVideo .......................... RUNNING
> subvert_1  |   2023-03-29 08:34:14 ................................................... ~ 1s
> subvert_1  |   2023-03-29 08:34:17 ................................................... ~ 1s
> subvert_1  |   2023-03-29 08:34:20 ................................................... ~ 1s
> subvert_1  |   2023-03-29 08:34:23 ................................................... ~ 0s
> subvert_1  |   2023-03-29 08:34:26 ................................................... ~ 1s
> subvert_1  |   2023-03-29 08:34:30 ................................................... ~ 0s
> subvert_1  |   2023-03-29 08:34:33 ................................................... ~ 0s
> subvert_1  |   2023-03-29 08:34:36 ................................................... ~ 0s
> subvert_1  |   2023-03-29 08:34:39 ................................................... ~ 0s
> subvert_1  |   2023-03-29 08:34:41 App\Jobs\ProcessVideo ................. 28,269.31ms DONE
> subvert_1  |   2023-03-29 08:34:42 ................................................... ~ 0s
> subvert_1  |   2023-03-29 08:36:33 ................................................... ~ 0s
> subvert_1  |   2023-03-29 08:36:33 /build/assets/app-73ca5879.css .................... ~ 0s
> subvert_1  |   2023-03-29 08:36:33 /build/assets/app-37ec3f69.css .................... ~ 0s
> subvert_1  |   2023-03-29 08:36:33 /build/assets/app-67abb96c.js ..................... ~ 0s
> subvert_1  |   2023-03-29 08:36:33 /favicon.ico ...................................... ~ 0s
> subvert_1  |   2023-03-29 08:36:54 ................................................... ~ 0s
> subvert_1  |   2023-03-29 08:36:57 App\Jobs\ProcessVideo .......................... RUNNING
> subvert_1  |   2023-03-29 08:36:57 ................................................... ~ 0s
> subvert_1  |   2023-03-29 08:36:58 App\Jobs\ProcessVideo .................. 1,186.94ms DONE
> subvert_1  |   2023-03-29 08:37:00 ................................................... ~ 0s

Is there something else I can do or try?

**Comment by antoninadert** [comment]
I had the same error.
```
When looking into the console, I found this object being sent : 
{
    "id": "5eb6183e-bf96-4fa2-b6f1-c040d4da19db",
    "status": 99,
    "options": {
        "subtitles": "true",
        "chapters": "false",
        "summary": "false",
        "language": "French",
        "chapters_amount": "5"
    },
    "file": "video/Ni7HBOKBLlbpRocW7pdQWzX3cJapwdgpa9JCm7bz.mp4",
    "error": "You exceeded your current quota, please check your plan and billing details.",
    "transcript": null,
    "summary": null,
    "chapters": null,
    "created_at": "2023-03-29T10:01:57.000000Z",
    "updated_at": "2023-03-29T10:02:02.000000Z",
    "message": "There was an error, check the console for more details"
}
```
Clearly the error was not returned upfront, and I guess you should check that you paid for OpenAI data.

Easy fix ?

**Comment by Entheologian** [comment]
Ahhh, the key, I completely missed that.. thanks.

**Comment by antoninadert** [comment]
Note that it took about an hour for me to work even after enabling the API and putting all billing details.

**Comment by aschmelyun** [comment]
@satoshinotdead is correct, this was due to a bug in the translation generator. Try again with the latest Docker image and that should fix it!
