### ISSUE TITLE
[Bug] Could not resolve host api.openai.com

### ISSUE THREAD

**Issue by Superpaul209** [aschmelyun/subvert#12]
Hello,

Im using the docker container to have the website available externally. Everything works fine except the last step of the process which is about the OpenAI API. When doing ```curl api.openai.com```, it doesn't work.

But with the ```nslookup``` command, I get a result : 
```/var/www/html # nslookup google.com
Server:         127.0.0.11
Address:        127.0.0.11:53

Non-authoritative answer:
Name:   google.com
Address: 142.250.74.174

** server can't find google.com: SERVFAIL
```

All my other containers can resolve any host successfully except this container. Is there an issue with my configuration or the container ?

Thanks for your help

**Comment by aschmelyun** [comment]
Unfortunately it sounds like an issue with your container(s), after verifying this isn't happening across a variety of platforms. Looks like they can't access external DNS. Try searching something along the lines of "Docker container can't resolve DNS", there's a few different threads above people experiencing similar issues with a variety of fixes.

Hope this helps!

**Comment by unitythemaker** [comment]
> Unfortunately it sounds like an issue with your container(s), after verifying this isn't happening across a variety of platforms. Looks like they can't access external DNS. Try searching something along the lines of "Docker container can't resolve DNS", there's a few different threads above people experiencing similar issues with a variety of fixes.
> 
> Hope this helps!

Okay thank you so much!
