### ISSUE TITLE
[Feature Request] Show max upload size

### ISSUE THREAD

**Issue by PinkFloyd1213** [aschmelyun/subvert#13]
Hi there!

I just wanted to say that I absolutely love the concept of Subvert. It's amazing how it generates subtitles, chapters, and summaries of videos so quickly with the help of OpenAI.

I recently noticed the latest update and thought of an option that would be in line with it. It would be great to display the value of the maximum upload environment variable on the upload page. This would allow users to see the maximum file size directly on the upload page. Additionally, it would be great to block uploads that exceed this limit to avoid bugs.

Thank you for creating such an amazing tool!

**Comment by aschmelyun** [comment]
This was a great issue @PinkFloyd1213, thanks for the advice!
