### ISSUE TITLE
[Feature Request] Translate the summaries and chapters too

### ISSUE THREAD

**Issue by PinkFloyd1213** [aschmelyun/subvert#14]
Hello again!

I just had another thought regarding Subvert. Since the subtitles are already being translated, it would make sense to have the option to translate the generated chapters and summaries as well, if the user selects the language option. This would save users time from having to manually translate these elements and provide a more complete translation of the video.

Just a suggestion to consider! Thanks again for creating such a helpful tool.

Best regards.

**Comment by aschmelyun** [comment]
This was definitely the intention, and will be fixed with #18. Closing this issue since this is in progress and being worked on in that other thread!
