### ISSUE TITLE
Reverse proxy upstream SSL not loading CSS [Bug]

### ISSUE THREAD

**Issue by xRoBoTx** [aschmelyun/subvert#15]
Tried to set up Subvert behind Nginx reverse proxy with HTTPS using wildcard certificate. Resources can not be loaded because they are hardcoded to be served as HTTP. 

![image](https://user-images.githubusercontent.com/28825932/229359938-7feb924c-c32f-41ed-8530-d9879fa4d5a9.png)
![subvert](https://user-images.githubusercontent.com/28825932/229359806-1bf813f2-8c57-48ce-8364-90c02a1abe01.png)

**Comment by satoshinotdead** [comment]
Tried to add a basic http to https redirect from Nginx?

I see the project built into Apache and I thought seen a similar approach.

**Comment by ateliershen** [comment]
@xRoBoTx may I know if you have solved this? I am also encountering this issue.

So far I have tried:

1. Adding a middleware to redirect all traffic to https
2. Changing the APP_URL from http://localhost to my production URL with https
3. Adding APP_URL in the .env file

But none of those seems to work. I am wondering if I missed something.

**Comment by pcloves** [comment]
> 

I have solved this issue. this is the configuration in: Nginx Proxy Manager -> Advanced
```
    location / {
        proxy_pass http://192.168.50.104:1080/;
        proxy_set_header Host             $http_host;
        proxy_set_header X-Real-IP        $remote_addr;  
        proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

       auth_basic           "closed site";
       auth_basic_user_file /config/access/.htpasswd;
       proxy_set_header Authorization ""; # stop nginx forwarding the basic auth header for nginx .htpasswd to grafana            https://github.com/grafana/grafana/issues/8314

        add_header 'Content-Security-Policy' 'upgrade-insecure-requests';
    }
```

the key point is: `add_header 'Content-Security-Policy' 'upgrade-insecure-requests';`

**Comment by xRoBoTx** [comment]
That actually worked! Thanks!
![image](https://user-images.githubusercontent.com/28825932/230380828-723b01f5-e0d9-4684-8b75-8d21a3c99b06.png)
