### ISSUE TITLE
No rendering of subtitles

### ISSUE THREAD

**Issue by sidneyki** [aschmelyun/subvert#20]
Hello,
I installed subvert in a docker that is running on ubuntu 22.04.I first tried drag and drop mp4 file from a network drive but it sits a step 1. Then I tried to drag and drop from a local drive. same issue, sits at step 1:  extracting audio. The mp4 file is only 1.4gb
In the docker log it says "Press Ctrl+C to stop the server
  2023-04-07 01:18:11 ................................................... ~ 0s
  2023-04-07 01:18:11 /build/assets/app-748f141e.css .................... ~ 0s
  2023-04-07 01:18:11 /build/assets/app-37ec3f69.css .................... ~ 0s
  2023-04-07 01:18:11 /build/assets/app-67abb96c.js ..................... ~ 0s
  2023-04-07 01:18:11 /favicon.ico ...................................... ~ 0s

I do not see any errors.  Any suggestions on how to resolve this?

**Comment by enrique131** [comment]
you mentioned the file is 1.4Gb. Have you updated the maximun when installing i hope?
"UPLOAD_MAX_FILESIZE - Changes PHP's UPLOAD_MAX_FILESIZE setting. Default: 256M" maybe that can help. If you have, i hope someone can give you a hand here. I am also trying to get a solution to my issue. Good luck

**Comment by aschmelyun** [comment]
First, you should now be seeing a more clear error in the frontend thanks to #10 being fixed. This error is likely stemming from the size of your upload. OpenAI's Whisper API can only handle files about 25mb in size. I'm working on implementing batching to work through this limit, you can track that progress on #24.
