### ISSUE TITLE
Edit the max upload size

### ISSUE THREAD

**Issue by Superpaul209** [aschmelyun/subvert#3]
Hello,

I have seen your project on Reddit, thanks for this awesome idea !
I would like to know if its possible to add a variable to choose the max upload size allowed for this web server for the Docker image. I want to translate a bigger video than 128 MB but I can't do it.

Thanks 🙂

**Comment by dnburgess** [comment]
Would also like to know what the process would be.

I believe the Reddit post that brought us here said that this was possible, but isn't documented anywhere in the repository or in the Reddit post at the time of posting this.

**Comment by wertercatt** [comment]
https://github.com/aschmelyun/subvert/blob/94ef8eb877d8a6ce065478bedb47d8fe7a533bbc/Dockerfile#L6

I think you just change this line and rebuild the docker image

**Comment by dnburgess** [comment]
> https://github.com/aschmelyun/subvert/blob/94ef8eb877d8a6ce065478bedb47d8fe7a533bbc/Dockerfile#L6
> 
> I think you just change this line and rebuild the docker image

That's good to know. Thanks!

I think, though, this should be an environmental variable to easier management.

**Comment by satoshinotdead** [comment]
You can add this line to docker compose file

See https://www.baeldung.com/ops/docker-compose-multiple-commands

**Comment by aschmelyun** [comment]
Done! There's now two new env arguments you can pass to your `docker run` command with `-e` flags:

- `UPLOAD_MAX_FILESIZE` - Changes PHP's UPLOAD_MAX_FILESIZE setting. Default: `256M`
- `MEMORY_LIMIT` - Changes PHP's MEMORY_LIMIT setting. Default: `512M`

You can try this out by pulling in the latest Docker image `docker pull aschmelyun/subvert:latest`

**Comment by dnburgess** [comment]
Awesome!!
